### ISSUE TITLE
connections not closing?

### ISSUE THREAD

**Issue by hading** [fcrepo4/fcrepo-message-consumer#79]
We're investigating the use of fedora with this service to index in solr and/or a triplestore. For now just solr. 

For my development set up I have fedora, solr, and fcrepo-message-consumer all running in different instances of jetty on OSX 10.10.

I do a small ingest of 5000 items into fedora including the rdf to have them indexed. 

Prior to running the ingest lsof | grep CLOSE_WAIT | wc shows about 10-20 lines.

I run the ingest. It completes successfully and the slower solr indexing continues for some time afterward. Repeating the above shows the CLOSE_WAIT count creeping up a little behind but in step with the number of items indexed in solr.

When the solr indexing is completed there are 5020 lines in CLOSE_WAIT, suggesting that there is one for each item that has been solr indexed.

This does not go down with time.

Killing fedora and solr it remains the same.

Killing fcrepo-message-consumer immediately drops it back down to the 20 range or so.

Initially I had tried a larger (10000 item) ingest, but this failed (on too many open files). 

Another test with the solr connector off but the file system connectors still on showed the same behavior; the ingest into fedora completes and the number of connections open continues to rise as the messages are picked up and the rdf is serialized to the filesystem. I had desired to run another test with no serializers, but for some reason I don't seem to be able to get mvn to build the project anymore. Not sure what that might be and don't want to figure it out right now.

I don't know if there is something I am doing wrong here or if it is an issue with fcrepo-message-consumer, but best to report it in case there is something amiss.

This is with git commit 5d6d9dc8d08be010dde8b8afa8a059f72c8c2655

**Comment by escowles** [comment]
I suspect this line is the culprit here:

https://github.com/fcrepo4/fcrepo-message-consumer/blob/master/fcrepo-message-consumer-core/src/main/java/org/fcrepo/indexer/IndexerGroup.java#L208

We should set the connection limits to something more reasonable and/or make them configurable.  I've opened a bug in JIRA to track this issue: https://jira.duraspace.org/browse/FCREPO-1401

**Comment by awoods** [comment]
Tracking issue in JIRA:
https://jira.duraspace.org/browse/FCREPO-1401
